import { NextRequest, NextResponse } from "next/server";
import archiver from "archiver";
import fs from "fs";
import path from "path";
import schemaDb from '@/lib/schema_blueprints_db.json';
import { Readable } from "stream";

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
    try {
        const resolvedParams = await params;
        const blueprintId = resolvedParams.id;

        // Find the blueprint rules in the database
        const blueprint = schemaDb.blueprints.find((b: any /* eslint-disable-line @typescript-eslint/no-explicit-any */) => b.id === blueprintId);

        if (!blueprint) {
            return new NextResponse("Blueprint ID not found in library.", { status: 404 });
        }

        // We use a stream to pipe the archiver execution directly into the Next.js HTTP Response
        // This is pure, low-level Node.js engineering enabling 0-infrastructure delivery

        const archive = archiver('zip', {
            zlib: { level: 9 } // Maximum compression
        });

        // Create a custom Readable stream that Vercel/NextJS can pipe to the client
        const stream = new ReadableStream({
            start(controller) {
                archive.on('data', (chunk) => controller.enqueue(chunk));
                archive.on('end', () => controller.close());
                archive.on('error', (err) => controller.error(err));
            }
        });

        // The path to our Golden Boilerplate
        const templatePath = path.join(process.cwd(), 'src', 'templates', 'nextjs-ai-router');

        if (!fs.existsSync(templatePath)) {
            throw new Error("Template repository missing from server.");
        }

        // Add all boilerplate files, specifically ignoring the route.ts we are going to auto-inject
        archive.glob('**/*', {
            cwd: templatePath,
            ignore: ['src/app/api/chat/route.ts']
        });

        // INJECTION: We read the generic route.ts to modify it
        const routeTsPath = path.join(templatePath, 'src', 'app', 'api', 'chat', 'route.ts');
        if (fs.existsSync(routeTsPath)) {
            let routeContent = fs.readFileSync(routeTsPath, 'utf8');

            const firstNodeKey = Object.keys(blueprint.stack)[0];
            const primaryModel = (blueprint.stack as any)[firstNodeKey].id;
            const primaryProvider = (blueprint.stack as any)[firstNodeKey].provider;

            routeContent = routeContent.replace('__CORE_ENGINE_ID__', primaryModel);
            routeContent = routeContent.replace('__CORE_ENGINE_PROVIDER__', primaryProvider);

            const injectedLogic = `
// AUTO-GENERATED BY GENERATIVE ARCHITECT
// Blueprint: ${blueprint.name}
// Description: ${blueprint.description}

export const GENERATIVE_CONSTRAINTS = ${JSON.stringify(blueprint.components, null, 4)};

// The architecture automatically falls back to OpenRouter models if specific native keys are missing
export const RECOMMENDED_STACK = ${JSON.stringify(blueprint.stack, null, 4)};
export const FALLBACK_STACK = ${JSON.stringify(blueprint.stack_openrouter_only, null, 4)};
`;

            routeContent = routeContent.replace("import { streamText } from 'ai';", "import { streamText } from 'ai';\n" + injectedLogic);

            // Specifically overwrite the zipped route.ts with our modified buffer
            archive.append(routeContent, { name: 'src/app/api/chat/route.ts' });
        }

        // Finalize the ZIP packing process
        archive.finalize();

        // Return the HTTP Stream Response (bypassing S3/disk entirely)
        return new NextResponse(stream, {
            headers: {
                "Content-Type": "application/zip",
                "Content-Disposition": `attachment; filename="${blueprintId}.zip"`,
            },
        });

    } catch (err: unknown) {
        console.error("ZIP Generation Error:", err);
        return new NextResponse("Failed to generate serverless ZIP. Please contact support.", { status: 500 });
    }
}
