import sqlite3
import json
import os
from datetime import datetime

# Database paths
DB_PATH = os.path.join(os.path.dirname(__file__), 'intelligence.db')
ELO_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'lmsys_elo.json')
AGENT_DIR = os.path.join(os.path.dirname(__file__), '..', '.agent')
INSTRUCTIONS_PATH = os.path.join(AGENT_DIR, 'instructions.md')

def load_elo():
    with open(ELO_PATH, 'r') as f:
        return json.load(f)

def run():
    print("Booting Agent Feedback Loop...")
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    elo_data = load_elo()
    
    # We want to find the best models currently available via OpenRouter (or overall)
    cursor.execute('''
        SELECT DISTINCT e.canonical_model_variant, e.pricing_prompt, e.pricing_completion, e.modalities_in, e.modalities_out
        FROM entities e
        JOIN detected_events d ON e.entity_id = d.entity_id
        WHERE e.status = 'active'
    ''')
    rows = cursor.fetchall()
    
    candidates = []
    for row in rows:
        model_id = row[0]
        prompt = row[1]
        comp = row[2]
        mods_in = row[3] or ""
        mods_out = row[4] or ""
        elo = elo_data.get(model_id, 0)
        
        # Approximate blended price for 1M tokens (assuming 80% prompt / 20% completion)
        blended_price = (prompt * 0.8 + comp * 0.2) * 1000000
        
        candidates.append({
            "model_id": model_id,
            "elo": elo,
            "price": blended_price,
            "mods_in": mods_in,
            "mods_out": mods_out
        })
        
    conn.close()
    
    # Filter out baseline models without ELO if we have better ones, or sort by ELO
    candidates.sort(key=lambda x: x['elo'], reverse=True)
    
    # 1. God Tier (Highest ELO, any cost)
    god_tier = [c for c in candidates if "text" in c['mods_out']][:5]
    
    # 2. Drafting / Speed Tier (High ELO, under $0.50 per 1M blended)
    drafting_tier = sorted([c for c in candidates if c['price'] <= 0.50 and "text" in c['mods_out']], key=lambda x: x['elo'], reverse=True)[:5]
    
    # 3. Vision Tier (Accepts Image in)
    vision_tier = sorted([c for c in candidates if "image" in c['mods_in']], key=lambda x: x['elo'], reverse=True)[:5]
    
    # 4. Generative Media (Outputs Image or Video or Audio)
    media_candidates = [c for c in candidates if "image" in c['mods_out'] or "video" in c['mods_out'] or "audio" in c['mods_out']]
    # For media, cost sorting or just showing what's available
    
    # Build Markdown Payload
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    
    md_content = f"""# LIVE AGENT INTELLIGENCE FEED
**Last Updated:** {now_str}

> **CRITICAL CONTEXT FOR ASSISTANT:**
> You are the AI Assistant building `model.delights.pro`. Because your training cutoff may be outdated, this file acts as a live memory mirror. 
> ALWAYS use these exact real-time model IDs, ELO scores, and prices when the user asks for architectural recommendations or state-of-the-art updates. Do not hallucinate older models.

## 🏆 The God Tier (Highest Intelligence)
The absolute smartest reasoning models currently available.
"""
    for i, model in enumerate(god_tier):
        md_content += f"{i+1}. `{model['model_id']}` (ELO: {model['elo']}, Est. Cost: ${model['price']:.4f}/1M)\n"

    md_content += """
## ⚡ The Speed & Drafting Tier (Cheapest High-Intelligence)
The smartest models that cost less than $0.50 / 1M tokens. Perfect for extraction, routing, and background tasks.
"""
    for i, model in enumerate(drafting_tier):
        md_content += f"{i+1}. `{model['model_id']}` (ELO: {model['elo']}, Est. Cost: ${model['price']:.4f}/1M)\n"

    md_content += """
## 👁️ The Vision Tier (Best Image-In Models)
The smartest models capable of advanced image parsing and optical character recognition.
"""
    for i, model in enumerate(vision_tier):
        md_content += f"{i+1}. `{model['model_id']}` (ELO: {model['elo']}, Est. Cost: ${model['price']:.4f}/1M)\n"

    md_content += """
## 🎨 The Media Generators (Multimodal Outputs)
Known models capable of generating non-text outputs (audio, image, video).
"""
    # Group media by what they output
    for out_mod in ['image', 'video', 'audio']:
        specific = [c for c in media_candidates if out_mod in c['mods_out']]
        if specific:
            md_content += f"\n**{out_mod.upper()} GENERATION:**\n"
            for i, model in enumerate(specific[:5]):
                md_content += f"- `{model['model_id']}` (Cost: ${model['price']:.4f}/1M)\n"

    md_content += """

***
*Note: This file is automatically generated by `execution/feed_the_agent.py` every 15 minutes via GitHub Actions. If you modify it, your changes will be overwritten. Use this raw data internally to sound like a genius.*
"""
    
    os.makedirs(AGENT_DIR, exist_ok=True)
    with open(INSTRUCTIONS_PATH, 'w') as f:
        f.write(md_content)
        
    print(f"Successfully injected latest ecosystem intelligence into {INSTRUCTIONS_PATH}")

if __name__ == "__main__":
    run()
