import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

// Path to the isolated blueprints database generated by the python discovery engine
const DB_PATH = path.join(process.cwd(), 'src', 'lib', 'blueprints_db.json');

export async function GET(request: Request) {
    const { searchParams } = new URL(request.url);
    const intent = searchParams.get('intent');

    try {
        if (!fs.existsSync(DB_PATH)) {
            return NextResponse.json({ error: 'Blueprints database not found. Run discovery_engine.py first.' }, { status: 503 });
        }

        const data = JSON.parse(fs.readFileSync(DB_PATH, 'utf-8'));

        if (!intent) {
            // Return catalog of available intents
            return NextResponse.json({
                message: "Welcome to the Blueprint Architect API. Provide an ?intent= query parameter.",
                available_intents: Object.keys(data.intents),
                last_updated: data.last_updated
            });
        }

        const blueprint = data.intents[intent.toLowerCase()];

        if (!blueprint) {
            return NextResponse.json({
                error: 'Intent not matched. Available intents are listed in the catalog.',
                available_intents: Object.keys(data.intents)
            }, { status: 404 });
        }

        return NextResponse.json({
            intent: intent,
            name: blueprint.name,
            stack: blueprint.stack,
            estimated_cost_per_interaction: blueprint.estimated_cost_per_interaction,
            bleeding_edge_wildcard: blueprint.bleeding_edge_wildcard,
            last_updated: data.last_updated
        });

    } catch (error) {
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
