import React, { useState } from 'react';

export interface SnellNodeConfig {
    id: string;
    intent: string;
    estimatedInputTokens: number;
    policy: string;
    capabilities: string[];
    cached_payload: boolean;
}

interface ExportModalProps {
    isOpen: boolean;
    onClose: () => void;
    nodes: SnellNodeConfig[];
}

export function ExportModal({ isOpen, onClose, nodes }: ExportModalProps) {
    const [activeTab, setActiveTab] = useState<'json' | 'ts' | 'yaml'>('ts');
    const [copied, setCopied] = useState(false);

    if (!isOpen) return null;

    const serializeNodes = () => {
        const obj: Record<string, Omit<SnellNodeConfig, 'id'>> = {};
        nodes.forEach(n => {
            const { id, ...rest } = n;
            // Only add capabilities if not empty
            const cleanRest = rest.capabilities.length === 0 ? { ...rest, capabilities: undefined } : rest;
            obj[id] = JSON.parse(JSON.stringify(cleanRest));
        });
        return obj;
    };

    const getJson = () => {
        return JSON.stringify({
            "$schema": "https://model.delights.pro/schema/snell-v1.json",
            "version": "1.0.0",
            "nodes": serializeNodes()
        }, null, 2);
    };

    const getTS = () => {
        return `// Output generated by the Snell Matrix Configurator
// https://model.delights.pro/configurator

import { SnellConfiguration } from 'model-delights-snell';

export const snellConfig: SnellConfiguration = {
    version: "1.0.0",
    nodes: ${JSON.stringify(serializeNodes(), null, 4).replace(/"([^"]+)":/g, '$1:')}
};
`;
    };

    const getYaml = () => {
        let yamlStart = `version: "1.0.0"\nnodes:\n`;
        nodes.forEach(n => {
            yamlStart += `  ${n.id}:\n`;
            yamlStart += `    intent: "${n.intent}"\n`;
            yamlStart += `    estimatedInputTokens: ${n.estimatedInputTokens}\n`;
            yamlStart += `    policy: "${n.policy}"\n`;
            yamlStart += `    cached_payload: ${n.cached_payload}\n`;
            if (n.capabilities.length > 0) {
                yamlStart += `    capabilities:\n`;
                n.capabilities.forEach(c => {
                    yamlStart += `      - "${c}"\n`;
                });
            }
        });
        return yamlStart;
    };

    const copyToClipboard = () => {
        let text = "";
        if (activeTab === 'json') text = getJson();
        if (activeTab === 'ts') text = getTS();
        if (activeTab === 'yaml') text = getYaml();

        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
            <div className="bg-[#111] border border-white/10 rounded-2xl w-full max-w-3xl shadow-2xl overflow-hidden flex flex-col">
                <div className="flex items-center justify-between p-4 border-b border-white/10">
                    <div>
                        <h2 className="text-xl font-bold text-white tracking-tight">Export Snell Configuration</h2>
                        <p className="text-sm text-white/50">Drop this file into your project root to enable White-Box routing.</p>
                    </div>
                    <button onClick={onClose} className="p-2 text-white/50 hover:text-white bg-white/5 rounded-md transition-colors">
                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <div className="flex px-4 pt-4 gap-4 bg-[#0a0a0a]">
                    <button 
                        onClick={() => setActiveTab('ts')} 
                        className={`pb-2 px-1 text-sm font-medium border-b-2 transition-colors ${activeTab === 'ts' ? 'border-primary text-primary' : 'border-transparent text-white/50 hover:text-white'}`}>
                        snell.config.ts
                    </button>
                    <button 
                        onClick={() => setActiveTab('json')} 
                        className={`pb-2 px-1 text-sm font-medium border-b-2 transition-colors ${activeTab === 'json' ? 'border-primary text-primary' : 'border-transparent text-white/50 hover:text-white'}`}>
                        snell.config.json
                    </button>
                    <button 
                        onClick={() => setActiveTab('yaml')} 
                        className={`pb-2 px-1 text-sm font-medium border-b-2 transition-colors ${activeTab === 'yaml' ? 'border-primary text-primary' : 'border-transparent text-white/50 hover:text-white'}`}>
                        snell.config.yaml
                    </button>
                </div>

                <div className="relative bg-[#0a0a0a] p-4 flex-1 overflow-auto min-h-[300px]">
                    <pre className="font-mono text-sm text-green-400 overflow-x-auto">
                        {activeTab === 'ts' && getTS()}
                        {activeTab === 'json' && getJson()}
                        {activeTab === 'yaml' && getYaml()}
                    </pre>

                    <button 
                        onClick={copyToClipboard}
                        className="absolute top-4 right-4 bg-white/10 hover:bg-white/20 backdrop-blur text-white text-xs px-3 py-1.5 rounded flex items-center gap-2 transition-all"
                    >
                        {copied ? (
                            <><svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg> Copied</>
                        ) : (
                            <><svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg> Copy Code</>
                        )}
                    </button>
                </div>
                
                <div className="p-4 border-t border-white/10 bg-[#111]">
                    <p className="text-xs text-white/40 mb-2 font-mono">Usage in code:</p>
                    <code className="text-xs text-white/60 bg-black p-2 rounded block font-mono border border-white/5">
                        {`import { IntelligenceRouter } from 'model-delights-snell';\nconst router = new IntelligenceRouter({ configPath: './snell.config' });\n\nawait router.execute("${nodes.length > 0 ? nodes[0].id : 'node_id'}", messages);`}
                    </code>
                </div>
            </div>
        </div>
    );
}
