import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'VacationTracker',
  description: 'Generated by Model Delights Generative Architect',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}