import { NextRequest, NextResponse } from "next/server";
import archiver from "archiver";

export async function POST(req: NextRequest) {
    try {
        const payload = await req.json();
        const { prdText, blueprint } = payload;

        if (!blueprint || !blueprint.name || !prdText) {
            return NextResponse.json({ error: "Invalid payload: Missing blueprint or PRD text." }, { status: 400 });
        }

        const safeProjectName = blueprint.name.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "agentic-scaffold";

        // Setup the Zip stream
        const archive = archiver('zip', {
            zlib: { level: 9 } // Sets the compression level.
        });

        // Convert archiver stream to standard React ReadableStream to work with Next.js App Router responses
        const stream = new ReadableStream({
            start(controller) {
                archive.on('data', (chunk) => controller.enqueue(chunk));
                archive.on('end', () => controller.close());
                archive.on('error', (err) => controller.error(err));
            }
        });

        // 1. package.json
        const packageJson = {
            name: safeProjectName,
            version: "0.1.0",
            private: true,
            scripts: {
                dev: "next dev",
                build: "next build",
                start: "next start",
                lint: "next lint"
            },
            dependencies: {
                react: "^18",
                "react-dom": "^18",
                next: "14.2.3",
                "lucide-react": "^0.378.0"
            },
            devDependencies: {
                typescript: "^5",
                "@types/node": "^20",
                "@types/react": "^18",
                "@types/react-dom": "^18",
                postcss: "^8",
                tailwindcss: "^3.4.1"
            }
        };

        // 2. README.md
        const readmeMd = `# ${blueprint.name} - Agentic Workspace

Welcome to your generated Software Seed! This repository is configured to be instantly actionable by AI code editors like Cursor, Bolt.diy, or Antigravity.

## How to use this folder:
1. Open this entire unzipped folder in your favorite AI Code Editor (e.g., Cursor, Windsurf, or Antigravity).
2. Open the AI Chat / Composer / Agent mode (e.g., \`Cmd + L\` or \`Cmd + I\` in Cursor).
3. Type the magic words: **"@.agent/instructions.md start building my app"**
4. Sit back and watch your AI CTO read the architectural blueprint and begin scaffolding the codebase!

*Generated by Model Delights Generative Architect.*
`;

        // 3. .agent/instructions.md
        const instructionsMd = `You are an elite Lead Engineer for this project. The founder has provided you with an Enterprise Architecture Blueprint and a rigorous Product Requirements Document (PRD).

Your task is to implement this system step-by-step.

# CONTEXT INGESTION:
Step 1. READ \`docs/prd.md\` to deeply understand the core user journey, the 3-tier feature breakdown, and the strict technical constraints.
Step 2. READ \`docs/architecture.json\` to understand the distributed microservices and the specific OpenRouter LLM nodes required.

# EXECUTION PLAN:
Step 3. RUN \`npm install\` to install the initial Next.js dependencies defined in \`package.json\`.
Step 4. INITIALIZE a standard Next.js App Router structure (\`src/app\`, etc.) and basic TailwindCSS config.
Step 5. SCAFFOLD the backend API routes matching the nodes defined in \`docs/architecture.json\`.
Step 6. BUILD the primary frontend UI to satisfy the "Core User Journey" defined in the PRD.
Step 7. IMPLEMENT full stack connectivity.

# CONSTRAINTS:
- Use TypeScript for everything.
- Use Tailwind for styling.
- Do not ask for redundant clarifications if the PRD or Architecture JSON already answers the question.
- Write robust, production-ready code.

Proceed immediately starting from Step 3.`;

        // Append files to archive
        archive.append(JSON.stringify(packageJson, null, 2), { name: `${safeProjectName}/package.json` });
        archive.append(readmeMd, { name: `${safeProjectName}/README.md` });
        archive.append(prdText, { name: `${safeProjectName}/docs/prd.md` });
        archive.append(JSON.stringify(blueprint, null, 2), { name: `${safeProjectName}/docs/architecture.json` });
        archive.append(instructionsMd, { name: `${safeProjectName}/.agent/instructions.md` });

        // Finalize the archive, which resolves the stream
        archive.finalize();

        // Send the compressed ZIP buffer to the client
        return new NextResponse(stream, {
            headers: {
                "Content-Type": "application/zip",
                "Content-Disposition": `attachment; filename="${safeProjectName}-agent-scaffold.zip"`,
            }
        });

    } catch (error: any) {
        console.error("Agent Scaffold Generation Error:", error);
        return NextResponse.json({ error: error.message || "Failed to generate agent scaffold zip" }, { status: 500 });
    }
}
