import { NextRequest, NextResponse } from "next/server";
import archiver from "archiver";

export async function POST(req: NextRequest) {
    try {
        const payload = await req.json();
        const { prdText, blueprint } = payload;

        if (!blueprint || !blueprint.name || !prdText) {
            return NextResponse.json({ error: "Invalid payload: Missing blueprint or PRD text." }, { status: 400 });
        }

        const safeProjectName = blueprint.name.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "agentic-scaffold";

        // Setup the Zip stream
        const archive = archiver('zip', {
            zlib: { level: 9 } // Sets the compression level.
        });

        // Convert archiver stream to standard React ReadableStream to work with Next.js App Router responses
        const stream = new ReadableStream({
            start(controller) {
                archive.on('data', (chunk) => controller.enqueue(chunk));
                archive.on('end', () => controller.close());
                archive.on('error', (err) => controller.error(err));
            }
        });

        // 1. package.json
        const packageJson = {
            name: safeProjectName,
            version: "0.1.0",
            private: true,
            scripts: {
                dev: "next dev",
                build: "next build",
                start: "next start",
                lint: "next lint"
            },
            dependencies: {
                react: "^18",
                "react-dom": "^18",
                next: "14.2.3",
                "lucide-react": "^0.378.0"
            },
            devDependencies: {
                typescript: "^5",
                "@types/node": "^20",
                "@types/react": "^18",
                "@types/react-dom": "^18",
                postcss: "^8",
                tailwindcss: "^3.4.1"
            }
        };

        // 2. README.md
        const readmeMd = `# ${blueprint.name} - Agentic Workspace

Welcome to your generated Software Seed! This repository is configured to be instantly actionable by AI code editors like Cursor, Bolt.diy, or Antigravity.

## How to use this folder:
1. Open this entire unzipped folder in your favorite AI Code Editor (e.g., Cursor, Windsurf, or Antigravity).
2. Open the AI Chat / Composer / Agent mode (e.g., \`Cmd + L\` or \`Cmd + I\` in Cursor).
3. Type the magic words: **"@.agent/instructions.md start building my app"**
4. Sit back and watch your AI CTO read the architectural blueprint and begin scaffolding the codebase!

*Generated by Model Delights Generative Architect.*
`;

        // 3. .agent/instructions.md
        const instructionsMd = `You are an elite Lead Engineer for this project. The founder has provided you with an Enterprise Architecture Blueprint and a rigorous Product Requirements Document (PRD).

Your task is to implement this system step-by-step.

# MANDATORY UX DIRECTIVE
Before you write a single line of frontend code or modify this application's layout, you MUST explicitly read the Manifesto:
👉 READ: \`.agent/ux-principles.md\`

You are explicitly forbidden from designing generic, unstyled, or static tables. 
You are explicitly forbidden from ignoring Stateful loading mechanisms (Skeletons/Empty states).
You must follow the "Precision Application Builder Manifest" defined in that document strictly.

# CONTEXT INGESTION:
Step 1. READ \`.agent/ux-principles.md\`
Step 2. READ \`docs/prd.md\` to deeply understand the core user journey, the 3-tier feature breakdown, and the strict technical constraints.
Step 3. READ \`docs/architecture.json\` to understand the distributed microservices and the specific OpenRouter LLM nodes required.

# EXECUTION PLAN:
Step 4. RUN \`npm install\` to install the initial Next.js dependencies defined in \`package.json\`.
Step 5. INITIALIZE a standard Next.js App Router structure (\`src/app\`, etc.) and basic TailwindCSS config.
Step 6. SCAFFOLD the backend API routes matching the nodes defined in \`docs/architecture.json\`.
Step 7. BUILD the primary frontend UI to satisfy the "Core User Journey" defined in the PRD.
Step 8. IMPLEMENT full stack connectivity.

# CONSTRAINTS:
- Use TypeScript for everything.
- Use Tailwind for styling.
- Do not ask for redundant clarifications if the PRD or Architecture JSON already answers the question.
- Write robust, production-ready code.

Proceed immediately starting from Step 4.`;

        // 4. next.config.mjs
        const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;`;

        // 5. tsconfig.json
        const tsConfig = `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`;

        // 6. src/app/layout.tsx
        const layoutTsx = `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${blueprint.name}',
  description: 'Generated by Model Delights Generative Architect',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`;

        // 7. src/app/page.tsx
        const pageTsx = `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24 bg-black text-white">
      <h1 className="text-4xl font-bold mb-4">${blueprint.name}</h1>
      <p className="text-zinc-400">Your AI-generated scaffolding is ready.</p>
      <div className="mt-8 p-4 bg-zinc-900 rounded-lg border border-zinc-800 text-sm font-mono">
        Open <span className="text-cyan-400">@.agent/instructions.md</span> in Cursor or Windsurf to begin.
      </div>
    </main>
  );
}`;

        // 8. src/app/globals.css
        const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;`;

        // 9. postcss.config.mjs
        const postcssConfig = `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
  },
};

export default config;`;

        // 10. tailwind.config.ts
        const tailwindConfig = `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;`;

        // 11. .agent/ux-principles.md
        const uxPrinciplesMd = `# The Precision Application Builder Manifest (App UX Principles)

## Role
Act as a World-Class Principal Product Engineer and Senior UX Architect. You build hyper-functional, "zero-friction" web applications and SaaS platforms. Every interface you produce should feel like a precision instrument—every click instantaneous, every layout mathematically balanced, every data-state accounted for. Eradicate all generic, clunky AI dashboard patterns. You do not build static pages; you build living software.

## Fixed Interaction System (NEVER CHANGE)
This is what makes the app feel like a premium SaaS rather than a weekend hackathon project, following the Kano Model of UX expectations.

### 1. The "Stateful" Trinity (Must-Be Requirements)
You must NEVER build a generic screen that assumes perfect data. Every view must have three designed states:
- **The Skeleton State:** Do not use spinning circles. Use pulsing grey rectangles ('animate-pulse bg-zinc-200 rounded') that mimic the shape of the data loading in.
- **The Empty State:** If a table or list has no data, center a beautifully designed empty state in the container: a subtle faded icon, a short descriptive text, and a primary CTA button.
- **The Populated State:** The actual data grid.

### 2. Micro-Interactions & Feedback (Performance Attributes)
- **Active Navigation:** The active sidebar/navbar item must have a distinct background and a bold font weight.
- **Hover Rows:** Every row in a list or table must have a subtle background shift on hover to help the user's eye track across columns.
- **Focus Rings:** Every input, button, and interactive element MUST have a highly visible focus ring for keyboard navigation (Accessibility / WCAG requirement).
- **Animation timing:** Keep micro-interaction durations crisp (200–300 ms).
- **Instant Optimism:** Buttons clicked to submit data should immediately shift to a disabled "Loading..." state with an inline spinner to prevent double-clicks.

### 3. Component Architecture (App Layout Primitives)
Assemble layouts using rigid, proven structural primitives. Do not arbitrarily center content.
- **The Shell:** Fixed width Sidebar (e.g. 240px). Top Bar with breadcrumbs and Global Search. Soft grey background ('bg-zinc-50'), placing the actual content inside crisp white structural cards to create depth.
- **The Command Grid:** Data must be aligned flawlessly: Numbers align right, text align left, badges/statuses align center.
- **Status Badges:** A status must never just be text. It must be a pill-shaped badge with semantic colors (e.g., Green for "Paid", Yellow for "Pending", Red for "Failed").
- **The Slide-Over Drawer:** For editing data or creating new objects, do NOT route to a completely new page. Instead, animate a slide-over panel from the right side of the screen.

### 4. Designing for Delight (Attractive Features)
When requested or applicable, inject "Delighters":
- **Predictive Assistance:** Auto-generate insights or suggest next steps instead of making the user dig for them.
- **Keyboard Shortcuts:** Power users love hitting 'Cmd+K' to search or navigating tables with arrows. 
- **Feedback Loops:** Use subtle toast notifications in the bottom right corner for success/error states instead of blocking modals.

**Execution Directive:** "Do not build a generic dashboard; build a digital instrument. Every click should feel intentional, every animation should feel weighted and professional. Eradicate all generic AI patterns."`;

        // Append files to archive
        archive.append(JSON.stringify(packageJson, null, 2), { name: `${safeProjectName}/package.json` });
        archive.append(readmeMd, { name: `${safeProjectName}/README.md` });
        archive.append(prdText, { name: `${safeProjectName}/docs/prd.md` });
        archive.append(JSON.stringify(blueprint, null, 2), { name: `${safeProjectName}/docs/architecture.json` });
        archive.append(instructionsMd, { name: `${safeProjectName}/.agent/instructions.md` });
        archive.append(uxPrinciplesMd, { name: `${safeProjectName}/.agent/ux-principles.md` });
        archive.append(nextConfig, { name: `${safeProjectName}/next.config.mjs` });
        archive.append(tsConfig, { name: `${safeProjectName}/tsconfig.json` });
        archive.append(layoutTsx, { name: `${safeProjectName}/src/app/layout.tsx` });
        archive.append(pageTsx, { name: `${safeProjectName}/src/app/page.tsx` });
        archive.append(globalsCss, { name: `${safeProjectName}/src/app/globals.css` });
        archive.append(postcssConfig, { name: `${safeProjectName}/postcss.config.mjs` });
        archive.append(tailwindConfig, { name: `${safeProjectName}/tailwind.config.ts` });

        // Finalize the archive, which resolves the stream
        archive.finalize();

        // Send the compressed ZIP buffer to the client
        return new NextResponse(stream, {
            headers: {
                "Content-Type": "application/zip",
                "Content-Disposition": `attachment; filename="${safeProjectName}-agent-scaffold.zip"`,
            }
        });

    } catch (error: unknown) {
        console.error("Agent Scaffold Generation Error:", error);
        return NextResponse.json({ error: (error as Error).message || "Failed to generate agent scaffold zip" }, { status: 500 });
    }
}
